[default.databases]
my_pg_db_name = { url = "postgres://${DB_NAME}" }
redis = { url = "redis://127.0.0.1:6379" }


[release.databases]
my_pg_db_name = { url = "postgres://${DB_NAME}" }
redis = { url = "redis://127.0.0.1:6379" }
